<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>iwindplus-user-center</artifactId>
        <groupId>com.iwindplus.user.center</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>iwindplus-user-center-test</artifactId>

    <name>iwindplus-user-center-test</name>
    <description>用户中心服务测试模块</description>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.iwindplus.user.center</groupId>
            <artifactId>iwindplus-user-center-server</artifactId>
        </dependency>
    </dependencies>
</project>
